apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: kubernetes-challenge
build:
  artifacts:
  - image: abdullahaki/py-application
    context: app
    docker:
      dockerfile: Dockerfile
      cacheFrom:
      - "python:3.7-alpine3.13"
deploy:
  kustomize:
    paths:
    - kubernetes
